# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: productpb/product.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='productpb/product.proto',
  package='productpb',
  syntax='proto3',
  serialized_options=b'Z.github.com/ronaldoafonso/productinfo/productpb',
  serialized_pb=b'\n\x17productpb/product.proto\x12\tproductpb\"\x1a\n\tProductID\x12\r\n\x05value\x18\x01 \x01(\t\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x32}\n\x0bProductInfo\x12\x36\n\naddProduct\x12\x12.productpb.Product\x1a\x14.productpb.ProductID\x12\x36\n\ngetProduct\x12\x14.productpb.ProductID\x1a\x12.productpb.ProductB0Z.github.com/ronaldoafonso/productinfo/productpbb\x06proto3'
)




_PRODUCTID = _descriptor.Descriptor(
  name='ProductID',
  full_name='productpb.ProductID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='productpb.ProductID.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='productpb.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='productpb.Product.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='productpb.Product.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='productpb.Product.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='productpb.Product.price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['ProductID'] = _PRODUCTID
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductID = _reflection.GeneratedProtocolMessageType('ProductID', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTID,
  '__module__' : 'productpb.product_pb2'
  # @@protoc_insertion_point(class_scope:productpb.ProductID)
  })
_sym_db.RegisterMessage(ProductID)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'productpb.product_pb2'
  # @@protoc_insertion_point(class_scope:productpb.Product)
  })
_sym_db.RegisterMessage(Product)


DESCRIPTOR._options = None

_PRODUCTINFO = _descriptor.ServiceDescriptor(
  name='ProductInfo',
  full_name='productpb.ProductInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=139,
  serialized_end=264,
  methods=[
  _descriptor.MethodDescriptor(
    name='addProduct',
    full_name='productpb.ProductInfo.addProduct',
    index=0,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_PRODUCTID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getProduct',
    full_name='productpb.ProductInfo.getProduct',
    index=1,
    containing_service=None,
    input_type=_PRODUCTID,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTINFO)

DESCRIPTOR.services_by_name['ProductInfo'] = _PRODUCTINFO

# @@protoc_insertion_point(module_scope)
