---
version: '3.7'

services:
  productinfo:
    build:
      context: .
    image: productinfo:1.0.2
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/ronaldoafonso/productinfo
    ports:
      - target: 50051
        published: 50051
        protocol: tcp
        mode: host
    networks:
       - grpcnet
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]

networks:
  grpcnet:
    name: grpcnet
...
